Repository EnableSecurity/wafw00f, pull requests merged in 2020-01, with the labels that each got.

#94 Add Azure Front Door Support
  wafw00f/plugins/frontdoor.py
  wafw00f/wafprio.py
Labels: enhancement, new features

#95 Feature Input / Output results to file
  setup.py
  wafw00f/main.py
Labels: enhancement, new features, triaged

#96 WIP: Adding I/O Feature to wafw00f
  docs/wafw00f.8
  wafw00f/lib/asciiarts.py
  wafw00f/main.py
Labels: new features, wip

#98 Minor Code Refactor
  wafw00f/lib/evillib.py
  wafw00f/main.py
Labels: code refactor, enhancement
